-- Migration: Add players table for Player Profile Generator
-- Created: 2025-11-24
-- Description: Creates table for storing football player profiles generated by n8n + Gemini API

-- Create players table
CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    position VARCHAR(100) NOT NULL,
    clubs TEXT[] NOT NULL DEFAULT '{}',  -- Array of club names
    characteristics TEXT NOT NULL,
    strengths TEXT NOT NULL,
    weaknesses TEXT NOT NULL,
    estimated_current_form TEXT NOT NULL,
    team VARCHAR(255),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_players_name ON players(name);
CREATE INDEX IF NOT EXISTS idx_players_team ON players(team);
CREATE INDEX IF NOT EXISTS idx_players_metadata ON players USING gin(metadata);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to call the function before update
CREATE TRIGGER update_players_updated_at BEFORE UPDATE ON players
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add comment to table
COMMENT ON TABLE players IS 'Profiles of Ekstraklasa football players generated by n8n workflow using Wikipedia + Gemini API';
COMMENT ON COLUMN players.clubs IS 'Array of club names from player career';
COMMENT ON COLUMN players.metadata IS 'Additional data: sources (URLs), generated_at, model name, prompt_version';
